import argparse
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from data_handling import FEATURE_COLUMNS


def split_by_session(df, test_session=None):
    sessions = sorted(df["session_id"].astype(str).unique())
    if len(sessions) < 2:
        raise ValueError(
            "At least two independent sessions are required. "
            "Never randomly split trials from one capture session."
        )

    test_session = test_session or sessions[-1]
    if test_session not in sessions:
        raise ValueError(f"Unknown test session {test_session}; choose from {sessions}")

    train = df[df["session_id"].astype(str) != test_session].copy()
    test = df[df["session_id"].astype(str) == test_session].copy()
    if set(test["label"]) - set(train["label"]):
        raise ValueError("The training sessions do not contain every test label")
    return train, test, test_session


def train_model(features_path, model_path, test_session=None):
    df = pd.read_csv(features_path)
    required = {"session_id", "trial_id", "label", *FEATURE_COLUMNS}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"Feature file is missing columns: {sorted(missing)}")

    train, test, held_out_session = split_by_session(df, test_session)
    pipeline = Pipeline(
        [
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            (
                "classifier",
                RandomForestClassifier(
                    n_estimators=300,
                    class_weight="balanced",
                    random_state=42,
                    n_jobs=-1,
                ),
            ),
        ]
    )
    pipeline.fit(train[FEATURE_COLUMNS], train["label"])
    predictions = pipeline.predict(test[FEATURE_COLUMNS])

    print(f"Held-out test session: {held_out_session}")
    print(classification_report(test["label"], predictions, zero_division=0))
    print("Confusion matrix:")
    labels = sorted(df["label"].unique())
    print(pd.DataFrame(
        confusion_matrix(test["label"], predictions, labels=labels),
        index=[f"actual_{label}" for label in labels],
        columns=[f"predicted_{label}" for label in labels],
    ))

    importances = pd.Series(
        pipeline.named_steps["classifier"].feature_importances_,
        index=FEATURE_COLUMNS,
    ).sort_values(ascending=False)
    print("\nFeature importance:")
    print(importances)

    destination = Path(model_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(
        {
            "pipeline": pipeline,
            "features": FEATURE_COLUMNS,
            "labels": labels,
            "held_out_session": held_out_session,
        },
        destination,
    )
    print(f"Saved model to {destination}")
    return pipeline


def main():
    parser = argparse.ArgumentParser(
        description="Train a session-separated WhatsApp traffic classifier."
    )
    parser.add_argument("features", help="Feature CSV generated by data_handling.py")
    parser.add_argument(
        "--model", default="artifacts/whatsapp_random_forest.joblib"
    )
    parser.add_argument("--test-session", help="Entire session reserved for testing")
    args = parser.parse_args()
    train_model(args.features, args.model, args.test_session)


if __name__ == "__main__":
    main()
